### ISSUE TITLE
DeferredEventArgs.Empty cannot be used concurrently or in chained events

### ISSUE THREAD

**Issue by iospulbe** [pedrolamas/DeferredEvents#1]
`DeferredEventArgs.Empty` is a static object and it potentially holds the same deferral object while completely independent async events are underway. This can lead to major interference - e.g., if one releases deferral another might no longer wait accordingly.

The fix to such scenarios, currently, is to disregard `DeferredEventArgs.Empty` and manually new the args object:
```
await MyEvent.InvokeAsync(sender, DeferredEventArgs.Empty);
```

The proper fix would be something like making `DeferredEventArgs.Empty` create a new object everytime it's used.

**Comment by pedrolamas** [comment]
First of all, thank you for flagging this and sorry it took me so much time in replying, but somehow this went under my radar...

Changing a field to a property is a considerable breaking change (IL change is not reflected for older references) so I decided best to just mark the `Empty` field obsolete and show a build error with indication to use `new DeferredEventArgs()` instead.
