### ISSUE TITLE
Repo Copy?

### ISSUE THREAD

**Issue by michael-hawker** [pedrolamas/DeferredEvents#3]
## What happened

FYI, looks like there's another copy of the repo someone made without crediting your work: https://github.com/tibel/DeferredEvents

Also, as we discussed, we [pulled this into the Toolkit repo](https://github.com/CommunityToolkit/WindowsCommunityToolkit/tree/main/Microsoft.Toolkit/Deferred) would we want to maintain it there moving forward together as part of the new [.NET Community Toolkit](https://devblogs.microsoft.com/ifdef-windows/welcome-to-the-community-toolkit/#%f0%9f%94%ae-the-future-introducing-the-net-community-toolkit) @Sergio0694 is going to help maintain?

I don't think you had unit tests at the time when we originally ported it over for UWP support, so those could be good to add on the Toolkit side as well.

**Comment by pedrolamas** [comment]
Thanks for the heads-up on the repo clone, I sure wasn't aware of that and truth be told, he has quite a few other clones on his profile... nevertheless, I've published this code with [MIT License](https://github.com/pedrolamas/DeferredEvents/blob/master/LICENSE.txt) so anyone can copy & alter without the need for any public attribution.

As for the .NET Community Toolkit, as we previously discussed that is now what I consider the de-facto owner/maintainer of the DeferredEvents code on this repo.

I kept this around as it targeted `netstandard1.0`, but I don't think that is a problem anymore as virtually there is nothing around that doesn't support at least `netstandard1.4`.

I will update the documentation (and blog posts) to point to the .NET Community Toolkit instead and then archive this repository along with the NuGet package.
